-- Extend the existing lineups table with professional pitch-lineup fields.
ALTER TABLE "lineups" ADD COLUMN IF NOT EXISTS "role" TEXT;
ALTER TABLE "lineups" ADD COLUMN IF NOT EXISTS "xPosition" DOUBLE PRECISION NOT NULL DEFAULT 50;
ALTER TABLE "lineups" ADD COLUMN IF NOT EXISTS "yPosition" DOUBLE PRECISION NOT NULL DEFAULT 50;
ALTER TABLE "lineups" ADD COLUMN IF NOT EXISTS "isCaptain" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "lineups" ADD COLUMN IF NOT EXISTS "isGoalkeeper" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "lineups" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
