import { cn } from "@/lib/utils";
import type { Standing } from "@/types";

function FormDots({ form }: { form?: string | null }) {
  const results = (form || "-----").padEnd(5, "-").slice(-5).split("");
  return <div className="flex items-center justify-center gap-0.5 sm:gap-1">{results.map((result, index) => <span key={index} className={cn("flex h-4 w-4 items-center justify-center rounded-full border text-[8px] font-bold sm:h-5 sm:w-5 sm:border-2 sm:text-[11px]", result === "W" ? "border-emerald-300 bg-emerald-500 text-white" : result === "D" ? "border-amber-300 bg-amber-500/20 text-amber-200" : result === "L" ? "border-rose-300 bg-rose-500/20 text-rose-200" : "border-slate-400 bg-transparent text-transparent")} aria-label={result === "-" ? "No result" : result}>{result === "W" ? "✓" : result === "D" ? "–" : result === "L" ? "×" : ""}</span>)}</div>;
}

export function LeagueStandingsTable({ standings, onTeamClick, className }: { standings: Standing[]; onTeamClick?: (standing: Standing) => void; className?: string }) {
  return <div className={cn("overflow-x-auto rounded-xl bg-[#202228] text-white shadow-sm", className)}><table className="w-full min-w-0 text-[10px] sm:min-w-[700px] sm:text-sm"><thead className="border-b border-white/15 text-[9px] text-slate-300 sm:text-[11px]"><tr><th className="w-5 px-1 py-2 text-center font-medium sm:w-12 sm:px-2 sm:py-3"> </th><th className="w-[92px] px-1 py-2 text-left font-medium sm:w-auto sm:px-2 sm:py-3">Club</th><th className="px-1 py-2 text-center font-medium sm:px-2 sm:py-3">MP</th><th className="px-1 py-2 text-center font-medium sm:px-2 sm:py-3">W</th><th className="px-1 py-2 text-center font-medium sm:px-2 sm:py-3">D</th><th className="px-1 py-2 text-center font-medium sm:px-2 sm:py-3">L</th><th className="px-1 py-2 text-center font-medium sm:px-2 sm:py-3">GF</th><th className="px-1 py-2 text-center font-medium sm:px-2 sm:py-3">GA</th><th className="px-1 py-2 text-center font-medium sm:px-2 sm:py-3">GD</th><th className="px-1 py-2 text-center font-semibold text-white sm:px-2 sm:py-3">Pts</th><th className="px-1 py-2 text-center font-medium sm:px-3 sm:py-3">Last 5</th></tr></thead><tbody>{standings.map((row) => <tr key={row.id} onClick={() => onTeamClick?.(row)} className={cn("border-b border-white/15 last:border-0", onTeamClick && "cursor-pointer hover:bg-white/5")}><td className="relative px-1 py-2 text-center font-semibold sm:px-2 sm:py-3"><span className={cn("absolute inset-y-0 left-0 w-1", row.position <= 2 ? "bg-sky-400" : row.position >= standings.length - 2 ? "bg-rose-500" : "bg-transparent")} />{row.position}</td><td className="max-w-[92px] px-1 py-2 sm:max-w-none sm:px-2 sm:py-3"><div className="flex items-center gap-1 sm:gap-2.5"><img src={row.team.logoUrl || "/placeholder.svg"} alt="" className="h-5 w-5 shrink-0 rounded-full bg-slate-700 object-cover sm:h-7 sm:w-7" /><span className="truncate font-medium">{row.team.name}</span></div></td><td className="px-1 py-2 text-center sm:px-2 sm:py-3">{row.played}</td><td className="px-1 py-2 text-center sm:px-2 sm:py-3">{row.wins}</td><td className="px-1 py-2 text-center sm:px-2 sm:py-3">{row.draws}</td><td className="px-1 py-2 text-center sm:px-2 sm:py-3">{row.losses}</td><td className="px-1 py-2 text-center sm:px-2 sm:py-3">{row.goalsFor}</td><td className="px-1 py-2 text-center sm:px-2 sm:py-3">{row.goalsAgainst}</td><td className="px-1 py-2 text-center sm:px-2 sm:py-3">{row.goalDifference}</td><td className="px-1 py-2 text-center font-bold sm:px-2 sm:py-3">{row.points}</td><td className="px-1 py-2 sm:px-3 sm:py-3"><FormDots form={row.form} /></td></tr>)}</tbody></table></div>;
}
