import { cn } from "@/lib/utils";
import type { Standing } from "@/types";

function FormDots({ form }: { form?: string | null }) {
  const results = (form || "-----").padEnd(5, "-").slice(-5).split("");
  return <div className="flex items-center justify-center gap-1">{results.map((result, index) => <span key={index} className={cn("flex h-5 w-5 items-center justify-center rounded-full border-2 text-[11px] font-bold", result === "W" ? "border-emerald-300 bg-emerald-500 text-white" : result === "D" ? "border-amber-300 bg-amber-500/20 text-amber-200" : result === "L" ? "border-rose-300 bg-rose-500/20 text-rose-200" : "border-slate-400 bg-transparent text-transparent")} aria-label={result === "-" ? "No result" : result}>{result === "W" ? "✓" : result === "D" ? "–" : result === "L" ? "×" : ""}</span>)}</div>;
}

export function LeagueStandingsTable({ standings, onTeamClick, className }: { standings: Standing[]; onTeamClick?: (standing: Standing) => void; className?: string }) {
  return <div className={cn("overflow-x-auto rounded-xl bg-[#202228] text-white shadow-sm", className)}><table className="w-full min-w-[700px] text-sm"><thead className="border-b border-white/15 text-[11px] text-slate-300"><tr><th className="w-12 px-2 py-3 text-center font-medium"> </th><th className="px-2 py-3 text-left font-medium">Club</th><th className="px-2 py-3 text-center font-medium">MP</th><th className="px-2 py-3 text-center font-medium">W</th><th className="px-2 py-3 text-center font-medium">D</th><th className="px-2 py-3 text-center font-medium">L</th><th className="px-2 py-3 text-center font-medium">GF</th><th className="px-2 py-3 text-center font-medium">GA</th><th className="px-2 py-3 text-center font-medium">GD</th><th className="px-2 py-3 text-center font-semibold text-white">Pts</th><th className="px-3 py-3 text-center font-medium">Last 5</th></tr></thead><tbody>{standings.map((row) => <tr key={row.id} onClick={() => onTeamClick?.(row)} className={cn("border-b border-white/15 last:border-0", onTeamClick && "cursor-pointer hover:bg-white/5")}><td className="relative px-2 py-3 text-center font-semibold"><span className={cn("absolute inset-y-0 left-0 w-1", row.position <= 2 ? "bg-sky-400" : row.position >= standings.length - 2 ? "bg-rose-500" : "bg-transparent")} />{row.position}</td><td className="px-2 py-3"><div className="flex items-center gap-2.5"><img src={row.team.logoUrl || "/placeholder.svg"} alt="" className="h-7 w-7 rounded-full bg-slate-700 object-cover" /><span className="font-medium">{row.team.name}</span></div></td><td className="px-2 py-3 text-center">{row.played}</td><td className="px-2 py-3 text-center">{row.wins}</td><td className="px-2 py-3 text-center">{row.draws}</td><td className="px-2 py-3 text-center">{row.losses}</td><td className="px-2 py-3 text-center">{row.goalsFor}</td><td className="px-2 py-3 text-center">{row.goalsAgainst}</td><td className="px-2 py-3 text-center">{row.goalDifference >= 0 ? row.goalDifference : row.goalDifference}</td><td className="px-2 py-3 text-center font-bold">{row.points}</td><td className="px-3 py-3"><FormDots form={row.form} /></td></tr>)}</tbody></table></div>;
}
