import { motion } from "framer-motion";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { api } from "@/lib/api";
import { formatDate, formatTime, formatCurrency } from "@/lib/utils";
import type { Booking, Payment } from "@/types";
import {
  X, User, Phone, MapPin, DollarSign, CreditCard,
  FileText, Clock, Calendar, Edit2, Ban, Undo2, Printer,
  AlertTriangle, CheckCircle2, MessageCircle,
} from "lucide-react";

function relativeTime(dateStr: string): string {
  const now = Date.now();
  const then = new Date(dateStr).getTime();
  const diff = now - then;
  const mins = Math.floor(diff / 60000);
  if (mins < 1) return "Just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 30) return `${days}d ago`;
  return formatDate(dateStr);
}

export function BookingDrawer({ booking, onClose }: { booking: Booking; onClose: () => void }) {
  const queryClient = useQueryClient();
  const statusColor = booking.status === "CONFIRMED" ? "bg-blue-500" :
    booking.status === "COMPLETED" ? "bg-green-500" :
    booking.status === "CANCELLED" ? "bg-red-500" :
    booking.status === "PENDING" ? "bg-amber-500" : "bg-purple-500";

  const handleAction = async (action: "confirm" | "cancel" | "refund") => {
    try {
      if (action === "confirm") await api.patch(`/admin/bookings/${booking.id}/status`, { status: "CONFIRMED" });
      else if (action === "cancel") await api.patch(`/admin/bookings/${booking.id}/status`, { status: "CANCELLED" });
      else if (action === "refund") await api.patch(`/admin/bookings/${booking.id}/status`, { status: "REFUNDED" });
      queryClient.invalidateQueries({ queryKey: ["admin-bookings"] });
      onClose();
    } catch {}
  };

  const handlePrintInvoice = () => {
    const printWin = window.open("", "_blank");
    if (!printWin) return;
    printWin.document.write(`
      <html><head><title>Invoice #${booking.bookingNumber}</title>
      <style>body{font-family:sans-serif;padding:40px;max-width:600px;margin:auto}
      h1{font-size:24px;margin-bottom:4px}.meta{color:#666;font-size:13px;margin-bottom:20px}
      table{width:100%;border-collapse:collapse;margin:20px 0}
      th,td{text-align:left;padding:8px 0;border-bottom:1px solid #ddd}
      .total{font-weight:bold;font-size:18px;text-align:right;margin-top:16px}
      .status{display:inline-block;padding:4px 12px;border-radius:99px;font-size:12px;background:#eee}
</style></head><body>
<h1>Invoice</h1><p class="meta">Booking #${booking.bookingNumber}<br>${formatDate(booking.date)}</p>
<table><tr><th>Customer</th><td>${booking.user?.firstName || ""} ${booking.user?.lastName || ""}</td></tr>
<tr><th>Phone</th><td>${booking.user?.phone || "—"}</td></tr>
<tr><th>Venue</th><td>${booking.turf?.venue?.name || "—"} / ${booking.turf?.name || "—"}</td></tr>
<tr><th>Time</th><td>${formatTime(booking.startTime)} – ${formatTime(booking.endTime)}</td></tr>
<tr><th>Duration</th><td>${booking.duration} hr${booking.duration > 1 ? "s" : ""}</td></tr></table>
<p class="total">Total: ${formatCurrency(booking.totalAmount)}</p>
<p><span class="status">${booking.status}</span></p>
<p style="margin-top:40px;font-size:12px;color:#999;text-align:center">Generated by Fusion League Admin</p>
</body></html>`);
    printWin.document.close();
    printWin.print();
  };

  const payments = booking.payments || [];

  return (
    <>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-40 bg-black/30 backdrop-blur-sm"
        onClick={onClose}
      />
      <motion.div
        initial={{ x: "100%" }}
        animate={{ x: 0 }}
        exit={{ x: "100%" }}
        transition={{ type: "spring", damping: 25, stiffness: 250 }}
        className="fixed right-0 top-0 z-50 h-full w-full max-w-lg border-l bg-background shadow-2xl overflow-y-auto"
      >
        <div className="sticky top-0 flex items-center justify-between border-b bg-background/95 backdrop-blur p-4 z-10">
          <div className="flex items-center gap-3">
            <h2 className="text-lg font-bold">Booking Details</h2>
            <Badge className={statusColor}>{booking.status}</Badge>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <X className="h-5 w-5" />
          </Button>
        </div>

        <div className="p-5 space-y-5">
          {/* Customer */}
          <div className="flex items-start gap-3 rounded-lg border p-4">
            <User className="mt-0.5 h-5 w-5 text-muted-foreground shrink-0" />
            <div className="min-w-0 flex-1">
              <p className="font-semibold">{booking.user?.firstName || "?"} {booking.user?.lastName || ""}</p>
              <p className="text-sm text-muted-foreground">{booking.user?.email || "—"}</p>
              {booking.user?.phone && (
                <p className="flex items-center gap-1.5 text-sm text-muted-foreground mt-0.5">
                  <Phone className="h-3.5 w-3.5" /> {booking.user.phone}
                </p>
              )}
            </div>
          </div>

          {/* Venue & Time */}
          <div className="flex items-start gap-3 rounded-lg border p-4">
            <MapPin className="mt-0.5 h-5 w-5 text-muted-foreground shrink-0" />
            <div>
              <p className="font-semibold">{booking.turf?.venue?.name || "Venue"}</p>
              <p className="text-sm text-muted-foreground">{booking.turf?.name} • {booking.turf?.size} • {booking.turf?.surface}</p>
              <div className="mt-1.5 flex items-center gap-4 text-sm text-muted-foreground">
                <span className="flex items-center gap-1"><Calendar className="h-3.5 w-3.5" />{formatDate(booking.date)}</span>
                <span className="flex items-center gap-1"><Clock className="h-3.5 w-3.5" />{formatTime(booking.startTime)} – {formatTime(booking.endTime)}</span>
              </div>
              <p className="text-xs text-muted-foreground mt-0.5">Duration: {booking.duration} hr{booking.duration > 1 ? "s" : ""} • {booking.numPlayers} players</p>
            </div>
          </div>

          {/* Amount & Payment */}
          <div className="flex items-start gap-3 rounded-lg border p-4">
            <DollarSign className="mt-0.5 h-5 w-5 text-muted-foreground shrink-0" />
            <div className="flex-1">
              <div className="flex items-center justify-between">
                <p className="font-semibold text-lg">{formatCurrency(booking.totalAmount)}</p>
                {payments.length > 0 && (
                  <Badge variant={payments[0].status === "PAID" ? "default" : payments[0].status === "REFUNDED" ? "secondary" : "outline"}>
                    {payments[0].status}
                  </Badge>
                )}
              </div>
              {booking.discountAmount > 0 && (
                <p className="text-sm text-green-600">Discount: –{formatCurrency(booking.discountAmount)}</p>
              )}
              {booking.couponCode && (
                <p className="text-xs text-muted-foreground">Coupon: {booking.couponCode}</p>
              )}

              {/* Payment History */}
              {payments.length > 0 && (
                <div className="mt-3 space-y-2">
                  <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground flex items-center gap-1">
                    <CreditCard className="h-3 w-3" /> Payments
                  </p>
                  {payments.map((p: Payment) => (
                    <div key={p.id} className="flex items-center justify-between rounded-md bg-muted/50 px-3 py-2 text-sm">
                      <div>
                        <span className="font-medium">{formatCurrency(p.amount)}</span>
                        <span className="ml-2 text-xs text-muted-foreground">{p.method || "—"}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        {p.transactionId && <span className="text-[10px] text-muted-foreground">#{p.transactionId.slice(0, 8)}</span>}
                        <Badge variant="outline" className="text-[10px]">{p.status}</Badge>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Notes */}
          {booking.notes && (
            <div className="flex items-start gap-3 rounded-lg border p-4">
              <FileText className="mt-0.5 h-5 w-5 text-muted-foreground shrink-0" />
              <div>
                <p className="text-sm font-medium">Notes</p>
                <p className="mt-1 text-sm text-muted-foreground">{booking.notes}</p>
              </div>
            </div>
          )}

          {/* Booking History Timeline */}
          <div className="rounded-lg border p-4">
            <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground flex items-center gap-1 mb-3">
              <Clock className="h-3 w-3" /> Booking History
            </p>
            <div className="space-y-0">
              {[
                { action: "Booking created", time: booking.createdAt, icon: CheckCircle2, color: "border-green-500 bg-green-500/20" },
                ...(booking.status === "CONFIRMED" || booking.status === "COMPLETED"
                  ? [{ action: "Booking confirmed", time: booking.updatedAt, icon: CheckCircle2, color: "border-blue-500 bg-blue-500/20" }]
                  : []),
                ...(booking.status === "CANCELLED"
                  ? [{ action: "Booking cancelled", time: booking.updatedAt, icon: Ban, color: "border-red-500 bg-red-500/20" }]
                  : []),
                ...(booking.status === "COMPLETED"
                  ? [{ action: "Booking completed", time: booking.updatedAt, icon: CheckCircle2, color: "border-green-500 bg-green-500/20" }]
                  : []),
              ].map((event, i, arr) => (
                <div key={i} className="relative flex gap-3 pb-4 last:pb-0">
                  {i < arr.length - 1 && (
                    <div className="absolute left-[7px] top-4 h-full w-px bg-border" />
                  )}
                  <div className={`mt-1.5 h-3.5 w-3.5 shrink-0 rounded-full border-2 ${event.color}`} />
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium">{event.action}</p>
                    <p className="text-xs text-muted-foreground">{event.time ? relativeTime(event.time) : "—"}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Actions */}
          <div className="space-y-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Actions</p>
            <div className="grid grid-cols-2 gap-2">
              {booking.status === "PENDING" && (
                <Button onClick={() => handleAction("confirm")} className="bg-green-600 hover:bg-green-700">
                  <CheckCircle2 className="mr-1.5 h-4 w-4" /> Confirm
                </Button>
              )}
              {(booking.status === "PENDING" || booking.status === "CONFIRMED") && (
                <Button variant="destructive" onClick={() => handleAction("cancel")}>
                  <Ban className="mr-1.5 h-4 w-4" /> Cancel
                </Button>
              )}
              {booking.status === "CONFIRMED" && (
                <Button variant="secondary" onClick={() => handleAction("refund")}>
                  <Undo2 className="mr-1.5 h-4 w-4" /> Refund
                </Button>
              )}
              <Button variant="outline" onClick={handlePrintInvoice}>
                <Printer className="mr-1.5 h-4 w-4" /> Print Invoice
              </Button>
              {(() => {
                const phone = booking.user?.phone?.replace(/[^0-9]/g, "");
                const template = booking.turf?.venue?.bookingMessageTemplate?.trim();
                if (!phone || !template) return null;
                const msg = template
                  .replace("{customer}", `${booking.user?.firstName || ""} ${booking.user?.lastName || ""}`.trim())
                  .replace("{venue}", booking.turf?.venue?.name || "")
                  .replace("{date}", formatDate(booking.date))
                  .replace("{startTime}", booking.startTime)
                  .replace("{endTime}", booking.endTime)
                  .replace("{amount}", formatCurrency(booking.totalAmount))
                  .replace("{bookingNumber}", booking.bookingNumber);
                return (
                  <a href={`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`} target="_blank" rel="noreferrer" className="w-full">
                    <Button variant="outline" className="w-full">
                      <MessageCircle className="mr-1.5 h-4 w-4" /> Send WhatsApp
                    </Button>
                  </a>
                );
              })()}
            </div>
          </div>
        </div>
      </motion.div>
    </>
  );
}
