ALTER TABLE "fixtures" ADD COLUMN IF NOT EXISTS "isFriendly" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "fixtures" ADD COLUMN IF NOT EXISTS "matchClockSeconds" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "fixtures" ADD COLUMN IF NOT EXISTS "matchClockStartedAt" TIMESTAMP(3);
