import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { api, publicApiUrl } from "@/lib/api";
import type { Season } from "@/types";
import { PageError, PageSkeleton } from "@/components/PageState";
import { Button } from "@/components/ui/button";
import { LeagueStandingsTable } from "@/components/league/LeagueStandingsTable";

type PublicPlayer = { id: string; slug: string; firstName: string; lastName: string; jerseyNumber: number | null; position: string | null; isActive: boolean };
type PublicTeam = { id: string; slug: string; name: string; logoUrl?: string; players: PublicPlayer[]; staff: Array<{ firstName: string; lastName: string; role: string }> };
type Stat = { playerId: string; player: PublicPlayer; team: { name: string }; appearances: number; goals: number; assists: number; minutesPlayed: number; yellowCards: number; redCards: number };
type Overview = { season: Season; generatedAt: string; summary: { teams: number; players: number; fixtures: number; completed: number; goals: number }; standings: any[]; teams: PublicTeam[]; playerStats: Stat[]; friendlyStats: Stat[]; fixtures: Array<{ id: string; matchDate: string; scheduledDate: string | null; kickoffTime: string | null; status: string; homeScore: number | null; awayScore: number | null; homeTeam: PublicTeam; awayTeam: PublicTeam; isFriendly: boolean; competition: { id: string; name: string } | null; goals: Array<{ minute: number; player: PublicPlayer; isOwnGoal: boolean; isPenalty: boolean }>; cards: Array<{ minute: number; type: string; player: PublicPlayer }> }>; competitions: Array<{ id: string; name: string }>; awards: Array<{ id: string; name: string; winner: PublicPlayer | null; winnerTeam: PublicTeam | null }> };
const playerName = (p: PublicPlayer) => `${p.firstName} ${p.lastName}`.trim();

export function SeasonOverviewPage() {
  const { slug } = useParams();
  const navigate = useNavigate();
  const [tab, setTab] = useState("overview"), [teamId, setTeamId] = useState(""), [competitionId, setCompetitionId] = useState(""), [friendly, setFriendly] = useState(false);
  const seasons = useQuery({ queryKey: ["public-seasons"], queryFn: () => api.get<Season[]>("/league/seasons") });
  const overview = useQuery({ queryKey: ["season-overview", slug], queryFn: () => api.get<Overview>(`/league/seasons/${slug}/overview`), enabled: !!slug, staleTime: 60000 });
  if (!slug) return <div className="mx-auto max-w-5xl space-y-5 px-4 py-8"><h1 className="text-3xl font-bold">Season archive</h1><p className="text-muted-foreground">Explore each season's table, results, squads, statistics and awards.</p>{seasons.isLoading ? <PageSkeleton /> : seasons.isError ? <PageError title="Seasons could not be loaded" onRetry={() => void seasons.refetch()} /> : <div className="grid gap-4 sm:grid-cols-2">{seasons.data?.map(s => <Link key={s.id} to={`/league/seasons/${s.slug}`} className="rounded-xl border bg-card p-5 transition hover:border-primary"><p className="text-lg font-semibold">{s.name}</p><p className="mt-2 text-sm text-muted-foreground">{s.startDate.slice(0,10)} — {s.endDate.slice(0,10)}</p><p className="mt-2 text-sm">{s.isCurrent ? "Current season" : "View season history"}</p></Link>)}</div>}<a className="inline-block text-sm underline" href={publicApiUrl("/league/seasons/index.html")}>Readable archive without JavaScript</a></div>;
  if (overview.isLoading) return <PageSkeleton />;
  if (overview.isError || !overview.data) return <PageError title="Season overview unavailable" description="Only published seasons are available in the archive." onRetry={() => void overview.refetch()} />;
  const data = overview.data;
  const fixtures = data.fixtures.filter(f => (!teamId || [f.homeTeam.id,f.awayTeam.id].includes(teamId)) && (!competitionId || f.competition?.id === competitionId));
  const stats = friendly ? data.friendlyStats : data.playerStats;
  return <div className="mx-auto max-w-7xl space-y-5 px-4 py-6 sm:px-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link to="/league/seasons" className="text-sm underline">All seasons</Link><label className="flex items-center gap-2 text-sm">Season<select className="rounded border bg-background p-2" value={slug} onChange={e => { setTeamId(""); setCompetitionId(""); navigate(`/league/seasons/${e.target.value}`); }}>{seasons.data?.map(s => <option key={s.id} value={s.slug}>{s.name}</option>)}</select></label></div>
    <section className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-xs font-semibold uppercase tracking-widest text-sky-300">{data.season.isCurrent ? "Current season" : "Season history"}</p><h1 className="mt-2 text-3xl font-bold">{data.season.name}</h1><p className="mt-2 text-sm text-slate-300">{data.season.startDate.slice(0,10)} — {data.season.endDate.slice(0,10)}</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5">{[["Teams",data.summary.teams],["Players",data.summary.players],["Matches",data.summary.fixtures],["Completed",data.summary.completed],["Goals (all matches)",data.summary.goals]].map(([label,value]) => <div key={label} className="rounded-lg bg-white/10 p-3"><p className="text-2xl font-bold">{value}</p><p className="text-xs text-slate-300">{label}</p></div>)}</div></section>
    <nav aria-label="Season details" className="flex gap-2 overflow-auto">{["overview","results","players","squads","awards"].map(t => <Button key={t} variant={tab === t ? "default" : "outline"} onClick={() => setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</Button>)}</nav>
    {tab === "overview" && <section className="overflow-hidden rounded-xl border bg-card"><h2 className="border-b p-4 font-semibold">Standings</h2><LeagueStandingsTable standings={data.standings} onTeamClick={row => navigate(`/league/teams/${row.team.slug}?seasonId=${data.season.id}`)} />{!data.standings.length && <p className="p-4 text-sm text-muted-foreground">No table entries recorded.</p>}<div className="border-t p-4 text-sm"><p>{data.competitions.map(c => c.name).join(" · ") || "League competition"}</p><p className="mt-2 text-muted-foreground">League player statistics and friendly statistics are separate. Open Results for match events and Squads for every registered player, including inactive players.</p></div></section>}
    {tab === "results" && <section className="space-y-3"><div className="flex flex-wrap gap-3"><label className="text-sm">Team <select className="rounded border bg-background p-2" value={teamId} onChange={e => setTeamId(e.target.value)}><option value="">All teams</option>{data.teams.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className="text-sm">Competition <select className="rounded border bg-background p-2" value={competitionId} onChange={e => setCompetitionId(e.target.value)}><option value="">All competitions</option>{data.competitions.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>{fixtures.map(f => <details key={f.id} className="rounded-xl border bg-card p-4"><summary className="cursor-pointer"><span className="text-xs text-muted-foreground">{(f.scheduledDate || f.matchDate.slice(0,10))} {f.kickoffTime} · {f.status}</span><p className="mt-1 font-semibold">{f.homeTeam.name} {f.homeScore ?? "–"} — {f.awayScore ?? "–"} {f.awayTeam.name}</p></summary><div className="mt-3 space-y-2 text-sm"><p>{f.competition?.name || (f.isFriendly ? "Friendly" : "League")}</p>{f.goals.map((g,i) => <p key={`goal-${i}`}>{g.minute}' · {playerName(g.player)} · {g.isOwnGoal ? "Own goal" : g.isPenalty ? "Penalty" : "Goal"}</p>)}{f.cards.map((c,i) => <p key={`card-${i}`}>{c.minute}' · {playerName(c.player)} · {c.type.replace(/_/g," ")}</p>)}<Link className="inline-block underline" to={`/league/fixtures/${f.id}`}>Full match details</Link></div></details>)}{!fixtures.length && <p>No matching fixtures.</p>}</section>}
    {tab === "players" && <section className="rounded-xl border bg-card p-4"><label className="mb-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={friendly} onChange={e => setFriendly(e.target.checked)} />Friendly statistics</label><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Player","Team(s)","Apps","Goals","Assists","Minutes","Yellow","Red"].map(h => <th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{stats.map(s => <tr key={s.playerId} className="border-t"><td className="p-2"><Link className="underline" to={`/league/players/${s.player.slug}?seasonId=${data.season.id}`}>{playerName(s.player)}</Link></td><td className="p-2">{s.team.name}</td>{[s.appearances,s.goals,s.assists,s.minutesPlayed,s.yellowCards,s.redCards].map((v,i) => <td key={i} className="p-2">{v}</td>)}</tr>)}</tbody></table></div>{!stats.length && <p className="p-4 text-sm">No statistics recorded.</p>}</section>}
    {tab === "squads" && <div className="grid gap-4 md:grid-cols-2">{data.teams.map(t => <section key={t.id} className="rounded-xl border bg-card p-4"><h2 className="font-semibold"><Link to={`/league/teams/${t.slug}?seasonId=${data.season.id}`}>{t.name}</Link></h2><ul className="mt-3 divide-y">{t.players.map(p => <li key={p.id} className="flex items-center justify-between gap-2 py-2 text-sm"><Link className="underline" to={`/league/players/${p.slug}?seasonId=${data.season.id}`}>{playerName(p)}</Link><span className="text-muted-foreground">{p.jerseyNumber != null ? `#${p.jerseyNumber} · ` : ""}{p.position || "Player"}{!p.isActive ? " · Inactive" : ""}</span></li>)}</ul><p className="mt-3 text-xs text-muted-foreground">Staff: {t.staff.map(s => `${s.firstName} ${s.lastName} (${s.role})`).join(", ") || "None listed"}</p></section>)}</div>}
    {tab === "awards" && <div className="grid gap-4 sm:grid-cols-2">{data.awards.map(a => <section key={a.id} className="rounded-xl border bg-card p-5"><h2 className="font-semibold">{a.name}</h2><p className="mt-2">{a.winner ? playerName(a.winner) : a.winnerTeam?.name || "Winner not announced"}</p></section>)}{!data.awards.length && <p>No awards recorded for this season.</p>}</div>}
    <footer className="flex flex-wrap gap-4 border-t pt-4 text-sm"><a className="underline" href={publicApiUrl(`/league/seasons/${slug}/overview.html`)}>Readable HTML</a><a className="underline" href={publicApiUrl(`/league/seasons/${slug}/overview`)}>Public JSON data</a><span className="text-muted-foreground">Updated {new Date(data.generatedAt).toLocaleString()}</span></footer>
  </div>;
}
