import { escapeHtml, type CalendarEntry } from "./images.js";

// Matches the app's default dark theme (client/src/index.css) and AdminCalendar
// status colours. Keep the export independent of browser sessions and preferences.
export function calendarHtml(venue: { name: string; timezone: string }, startDate: string, endDate: string, bookings: CalendarEntry[], audience: "public" | "staff") {
  const days: string[] = [];
  for (let instant = Date.parse(`${startDate}T00:00:00Z`); instant <= Date.parse(`${endDate}T00:00:00Z`); instant += 86400_000) days.push(new Date(instant).toISOString().slice(0, 10));
  const active = bookings.filter(booking => booking.status !== "CANCELLED");
  const clockLabel = (time: string) => { const [hour, minute] = time.split(":").map(Number); return `${hour % 12 || 12}:${String(minute).padStart(2, "0")} ${hour < 12 ? "AM" : "PM"}`; };
  const minutes = (booking: CalendarEntry) => booking.duration ?? (() => { const [sh, sm] = booking.startTime.split(":").map(Number), [eh, em] = booking.endTime.split(":").map(Number); const difference = (eh - sh) * 60 + em - sm; return difference > 0 ? difference : difference + 1440; })();
  const hours = Math.round(active.reduce((sum, booking) => sum + minutes(booking), 0) / 60 * 100) / 100;
  const bookedDays = new Set(active.map(booking => booking.date.toISOString().slice(0, 10))).size;
  const singleDay = days.length === 1;
  const start = new Date(`${startDate}T00:00:00Z`), end = new Date(`${endDate}T00:00:00Z`);
  const month = new Intl.DateTimeFormat("en", { month: "long", year: "numeric", timeZone: "UTC" });
  const title = startDate.slice(0, 7) === endDate.slice(0, 7) ? month.format(start) : `${month.format(start)} – ${month.format(end)}`;
  const generatedLabel = new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: venue.timezone }).format(new Date());
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: venue.timezone, year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  const leading = singleDay ? 0 : start.getUTCDay();
  const trailing = singleDay ? 0 : (7 - (leading + days.length) % 7) % 7;
  const blanks = (count: number) => '<div class="day outside" aria-hidden="true"></div>'.repeat(count);
  const cards = days.map(day => {
    const entries = active.filter(booking => booking.date.toISOString().slice(0, 10) === day);
    const date = new Date(`${day}T00:00:00Z`);
    const dateLabel = singleDay ? new Intl.DateTimeFormat("en", { weekday: "long", day: "numeric", month: "long", timeZone: "UTC" }).format(date) : String(date.getUTCDate());
    return `<section class="day${entries.length ? " booked" : ""}${day === today ? " today" : ""}" data-date="${day}"><div class="day-heading"><h2>${escapeHtml(dateLabel)}</h2>${entries.length ? `<span class="count">${entries.length} ${entries.length === 1 ? "booking" : "bookings"}</span>` : ""}</div>${entries.length ? entries.map(booking => {
      const status = audience === "public" ? "booked" : booking.status.toLowerCase();
      const customer = booking.customerName || [booking.user?.firstName, booking.user?.lastName].filter(Boolean).join(" ") || "Customer";
      return `<article class="slot ${escapeHtml(status)}"><div class="slot-top"><span class="status"><i></i>${escapeHtml(status)}</span></div><strong class="time">${escapeHtml(clockLabel(booking.startTime))}–${escapeHtml(clockLabel(booking.endTime))}${booking.endTime <= booking.startTime ? " (+1 day)" : ""}</strong>${audience === "staff" ? `<p class="customer">${escapeHtml(customer)}</p>` : ""}<p class="turf">${escapeHtml(booking.turf.name)}</p>${audience === "staff" && booking.bookingNumber ? `<p class="reference">${escapeHtml(booking.bookingNumber)}</p>` : ""}</article>`;
    }).join("") : '<p class="empty">No bookings</p>'}</section>`;
  }).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><style>
    :root{--background:hsl(222 47% 5%);--card:hsl(222 38% 10%);--foreground:hsl(210 40% 98%);--muted:hsl(215 20% 72%);--border:hsl(222 26% 24%);--primary:hsl(142 76% 55%)}
    *{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:var(--background);color:var(--foreground)}main{width:${singleDay ? 1000 : 1600}px;padding:32px;background:var(--background)}
    header{border:1px solid var(--border);border-top:3px solid var(--primary);border-radius:8px;padding:26px 28px;background:var(--card)}.brand{display:flex;align-items:center;justify-content:space-between;margin-bottom:24px}.wordmark{font-size:20px;font-weight:800;letter-spacing:.07em}.wordmark span{color:var(--primary)}.copy{padding:6px 10px;border:1px solid var(--border);border-radius:6px;color:var(--muted);font-size:12px;letter-spacing:.08em}
    .heading{display:flex;align-items:center;justify-content:space-between;gap:24px}h1{font-size:34px;letter-spacing:-.03em;margin:0 0 6px}.subtitle{color:var(--muted);font-size:16px;margin:0;line-height:1.6}.range{font-size:14px;color:var(--muted);margin:6px 0 0}.summary{font-size:15px;margin:20px 0 0;color:var(--primary)}.stats{display:flex;gap:14px}.stat{min-width:135px;border:1px solid var(--border);background:hsl(222 30% 16%);border-radius:8px;padding:14px 18px}.stat strong{display:block;font-size:28px;line-height:1.2}.stat span{display:block;color:var(--muted);font-size:12px;margin-top:6px}
    .legend{display:flex;gap:22px;align-items:center;padding:20px 2px;font-size:14px;color:var(--muted)}.legend span{display:flex;gap:8px;align-items:center}.legend i,.status i{width:7px;height:7px;border-radius:50%;background:currentColor;display:inline-block}.legend .confirmed{color:#93c5fd}.legend .pending{color:#fcd34d}.legend .rescheduled{color:#d8b4fe}.legend .completed,.legend .booked{color:#86efac}
    .calendar{border:1px solid var(--border);border-radius:8px;overflow:hidden}.weekdays,.grid{display:grid;grid-template-columns:repeat(${singleDay ? 1 : 7},1fr);gap:1px;background:var(--border)}.weekdays div{text-align:center;padding:13px;background:var(--card);color:var(--muted);font-size:13px;font-weight:600;letter-spacing:.05em}.grid{border-top:${singleDay ? 0 : 1}px solid var(--border)}.day{background:var(--background);padding:12px;min-height:${singleDay ? 220 : 150}px;min-width:0}.day.booked{background:hsl(222 38% 10%)}.day.outside{background:hsl(222 40% 7%)}.day-heading{display:flex;align-items:center;justify-content:space-between;gap:6px;min-height:26px;margin-bottom:8px}h2{font-size:${singleDay ? 20 : 17}px;margin:0;font-weight:600}.today h2{border-radius:5px;background:var(--primary);color:var(--background);padding:4px 7px}.count{font-size:11px;color:#93c5fd;background:#1e3a8a55;padding:3px 6px;border-radius:4px;white-space:nowrap}
    .slot{border:1px solid #1d4ed8;border-left:3px solid #3b82f6;background:#1e3a8a4d;color:#bfdbfe;border-radius:6px;padding:${singleDay ? 15 : 10}px;margin-top:8px;overflow-wrap:anywhere}.slot.pending{border-color:#a16207;border-left-color:#f59e0b;background:#78350f4d;color:#fcd34d}.slot.rescheduled{border-color:#7e22ce;border-left-color:#a855f7;background:#581c874d;color:#d8b4fe}.slot.completed,.slot.booked{border-color:#15803d;border-left-color:#22c55e;background:#14532d4d;color:#86efac}.slot-top{margin-bottom:6px}.status{display:flex;align-items:center;gap:6px;text-transform:capitalize;font-size:${singleDay ? 13 : 10}px;font-weight:600;letter-spacing:.04em}.time{display:block;font-size:${singleDay ? 20 : 13}px;line-height:1.55;font-variant-numeric:tabular-nums}.slot p{margin:4px 0 0;line-height:1.5}.customer{color:var(--foreground);font-size:${singleDay ? 19 : 13}px;font-weight:600}.turf{font-size:${singleDay ? 15 : 12}px}.reference{font-size:${singleDay ? 12 : 10}px;color:var(--muted)}.empty{font-size:12px;color:#68788e;margin:14px 0}.foot{display:flex;justify-content:space-between;gap:20px;margin-top:18px;color:var(--muted);font-size:12px;line-height:1.6}.foot p{margin:0}.privacy{color:#fcd34d}
    </style></head><body><main><header><div class="brand"><div class="wordmark">FUSION <span>TURF</span></div><span class="copy">${audience === "staff" ? "STAFF BOOKING CALENDAR" : "BOOKED SLOTS"}</span></div><div class="heading"><div><h1>${escapeHtml(title)}</h1><p class="subtitle">${escapeHtml(venue.name)} · ${escapeHtml(venue.timezone)}</p><p class="range">${escapeHtml(startDate)} — ${escapeHtml(endDate)}</p></div><div class="stats"><div class="stat"><strong>${active.length}</strong><span>Bookings</span></div><div class="stat"><strong>${hours}</strong><span>Hours booked</span></div><div class="stat"><strong>${bookedDays}</strong><span>Booked days</span></div></div></div><p class="summary">${active.length} ${active.length === 1 ? "booking" : "bookings"} · ${hours} ${hours === 1 ? "hour" : "hours"} booked</p></header><div class="legend">${audience === "staff" ? '<span class="confirmed"><i></i>Confirmed</span><span class="pending"><i></i>Pending</span><span class="completed"><i></i>Completed</span><span class="rescheduled"><i></i>Rescheduled</span>' : '<span class="booked"><i></i>Booked</span>'}<span>Times are venue-local</span></div><div class="calendar">${singleDay ? "" : `<div class="weekdays">${["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map(day => `<div>${day}</div>`).join("")}</div>`}<div class="grid">${blanks(leading)}${cards}${blanks(trailing)}</div></div><footer class="foot"><p>Generated ${escapeHtml(generatedLabel)}<br>Live booking snapshot · Availability may change</p><p class="privacy">${audience === "staff" ? "Contains customer details · Share with staff only" : "Public copy · Customer details hidden"}</p></footer></main></body></html>`;
}
