ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'PAUSED';
ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'HALF_TIME';
ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'EXTRA_TIME';
ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'PENALTIES';
